# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andy Barajas
title: Software Engineer / Data Analyst
email: andy@barajas-research.com
website: barajas123.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  barajas123
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 404_NOT_FOUND
linkedin_username: andy-barajas-b7b78088
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 404_NOT_FOUND
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_go.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Andy and I'm a Software Engineer. I also build and design microservices with experience in data analysis and a strong interest in the quantatative space. I have worked on building my own ETL pipelines and services related to the Financial Sector. I have spent the last 3 years learning technologies that are needed to complete requirements.

  I am skilled in: <mark>Golang, Microservices, Docker, Docker Swarm, Kubernetes</mark> and <mark> Python </mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: go-lib-td-data
        link: github.com/barajas123/go-lib-td-data
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         This repo has come in handy plenty of times
        description: | # this will include new lines to allow paragraphs
         This project was aimed to make future projects easier, allowing for easy Historical Price and real time price retrievel for real time analysis.
    content:
      - layout: top-middle
        title: MatchingGame.Net
        link: github.com/barajas123/MatchingGame.Net
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         This project was good practice to get the basics of C# down 
        description: | # this will include new lines to allow paragraphs
         The game consists of 16 square. All of which contain a matching icon. Steps ...
          1. Click any square to reveal the icon
          2. Click another square to reveal a second icon
          3. If they match, they will stay revealed. if not, they are both covered once again
          4. Keep playing until you match all square in a consecutive manner.
    content:
      - layout: top-middle
        title: LRU Cache
        link: github.com/barajas123/legendary-sniffle
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         Implement LRU Cache
        description: | # this will include new lines to allow paragraphs
         This projects shows how to implement an In Memory Cache with a LRU policy. This is implemented using a doubly linked list as the underlying data structure.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Barajas Research
        link: 
        # link_text: boringcompany.com
        sub_title: Software Engineer / Data Analyst
        caption: November 2018 - Present
        quote: > 
          Data Analysis is much like looking for gold, at some point you just have to pick up the shovel and start digging.
        description: | # this will include new lines to allow paragraphs
         Designing / Building / Maintaining ETL pipelines and microservices that are going to be provided to customer as a paid service.
          Technologies used:
          - Golang
          - Docker Swarm
          - Postgres
          - Linode Cloud Services
          - CentOS
          - Python 
          - VueJS
          - Micoservices 
          - Redis
          - RabbitMQ
          - Apache Kafka
          - Zookeeper
      - layout: left
        title: Polygon IO
        link: polygon.io
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: April 2020 - May 2020
        quote: >
          Democratizing financial data for the masses.
        description: | # this will include new lines to allow paragraphs
          Providing data via REST endpoints and WSS. Maintaining legacy repositories and rewriting from NodeJs to Golang for improved efficiency and scale. Unit testing all repos and updating / adding documentation. 
          Technologies used:
          - Golang
          - NodeJs
          - Kubernetes
          - Kafka
          - MongoDB
          - Drone CI / CD 
                  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in microservices and software engineering some of my other interests and hobbies are:
      - Data Analysis
      - Deep Neural Networks
      - Watching Stats videos on YT
      - 3D Printing
      - Golfing
    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
